spring.application.name=kursovaya

spring.datasource.url=jdbc:postgresql://localhost:5432/kursovaya_machine_factory
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

#spring.data.jdbc.repositories.enabled=true
#logging.level.org.springframework.jdbc.core=DEBUG